name: Hello World!

on: [push, pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello World!"

      - name: Now it is
        run: date

      - name: Directory contents
        run: ls -l
