name: Hello World!

on: [push, pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Say Hello World
        run: echo "Hello World!"
      
